// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package products

// Benefit defines model for Benefit.
type Benefit struct {
	AlternativeName         *string      `json:"alternative_name,omitempty"`
	ClaimRequiredDocuments  *interface{} `json:"claim_required_documents,omitempty"`
	ClaimSupportedDocuments *interface{} `json:"claim_supported_documents,omitempty"`
	Description             string       `json:"description"`
	Id                      float32      `json:"id"`
	Logo                    string       `json:"logo"`
	Name                    string       `json:"name"`
	Type                    string       `json:"type"`
}

// BenefitResponse defines model for BenefitResponse.
type BenefitResponse struct {
	Data  Benefit `json:"data"`
	Error Error   `json:"error"`
}

// Documents defines model for Documents.
type Documents struct {
	Code        string  `json:"code"`
	Description string  `json:"description"`
	Id          float32 `json:"id"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Insurance defines model for Insurance.
type Insurance struct {
	Code string  `json:"code"`
	Id   float32 `json:"id"`
	Logo string  `json:"logo"`
	Name string  `json:"name"`
}

// Products defines model for Products.
type Products struct {
	AdminFee                  float32   `json:"admin_fee"`
	Benefits                  *Benefit  `json:"benefits,omitempty"`
	CategoryCode              string    `json:"category_code"`
	CategoryName              string    `json:"category_name"`
	ClaimDescription          string    `json:"claim_description"`
	Country                   string    `json:"country"`
	CreatedAt                 string    `json:"created_at"`
	Currency                  *string   `json:"currency,omitempty"`
	HardcopyAdminFee          float32   `json:"hardcopy_admin_fee"`
	Id                        string    `json:"id"`
	Insurance                 Insurance `json:"insurance"`
	IsActive                  bool      `json:"is_active"`
	IsRenewalProduct          bool      `json:"is_renewal_product"`
	Language                  string    `json:"language"`
	ParentCategory            string    `json:"parent_category"`
	PartnerCode               string    `json:"partner_code"`
	Premium                   float32   `json:"premium"`
	PremiumUnitDuration       *string   `json:"premium_unit_duration,omitempty"`
	PremiumUnitDurationAmount *float32  `json:"premium_unit_duration_amount,omitempty"`
	ProductCode               string    `json:"product_code"`
	ProductDescription        string    `json:"product_description"`
	ProductName               string    `json:"product_name"`
	ProductSummary            string    `json:"product_summary"`
	ProductTerms              string    `json:"product_terms"`
	TaxFee                    float32   `json:"tax_fee"`
	UpdatedAt                 string    `json:"updated_at"`
}

// CreateProductJSONBody defines parameters for CreateProduct.
type CreateProductJSONBody Products

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody CreateProductJSONBody
